# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-10 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_pwa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pwa',
            name='icon_src_1',
            field=models.CharField(default='added later', max_length=200),
        ),
        migrations.AddField(
            model_name='pwa',
            name='sizes',
            field=models.CharField(default='added later', max_length=200),
        ),
        migrations.AddField(
            model_name='pwa',
            name='type_of_icon',
            field=models.CharField(default='added later', max_length=200),
        ),
    ]
